### ISSUE TITLE
Scaling and verbose arguments are ignored.

### ISSUE THREAD

**Issue by teej043** [akoenig/gulp-svg2png#11]
I am adding this gulp-svg2png to my build system workflow. It converts svg files and creates the png files, but somehow it does not scale the png nor show logs. 

```
gulp.task('svg2png', function () {
  return gulp.src('src/images/{,*/}*.svg')
    .pipe(svg2png({
      scaling : 0.5,
      verbose : true
    }))
    .pipe(gulp.dest('src/images/'));
});
```

I am also using gulp-imagemin as a dev dependency as well, does it have anything to do why scaling pngs not working on svg2png? Im on a windows7 machine.

**Comment by amaroyche** [comment]
Try it like this
```
gulp.task('svg2png', function () {
  return gulp.src('src/images/{,*/}*.svg')
    .pipe(svg2png(0.5,true))
    .pipe(gulp.dest('src/images/'));
});
```

**Comment by cikoriicabachkov** [comment]
@akoenig please, add this example in README or update plugin to use options like an object.

**Comment by akoenig** [comment]
Done in `2.0.0` :)
