### ISSUE TITLE
Support other projects with TypeScript type definitions (*.d.ts)

### ISSUE THREAD

**Issue by Sweetchuck** [akoenig/gulp-svg2png#17]
The problem is that even though _gulp-svg2png_ is written in TypeScript there is no generated `*.d.ts` files in the provided package.

**tsconfig.json** should contains a flag like this:
``` json
{
  "compilerOptions": {
    "declaration": true
  }
}
```

**.npmignore** Prevent to get excluded the `*.d.ts` files.
``` gitignore
!*.d.ts
```

Then the `tsd link` should work as designed or you can provide TS type definitions on [typings/typings](https://github.com/typings/typings) and [typings/registry](https://github.com/typings/typings)

**Comment by akoenig** [comment]
Thanks for the heads up. Done in `v2.0.0` :)

**Comment by Sweetchuck** [comment]
:smile:  :+1:
