### ISSUE TITLE
Latest svg2png patch breaks node 4 compatibility 

### ISSUE THREAD

**Issue by mrkiffie** [akoenig/gulp-svg2png#27]
Hi

The latest [patch](https://github.com/domenic/svg2png/commit/c266004443015777c6827138050dad0ac7e54cb2#diff-e6cb7d06781cf12f8e2d82b6ebdf7061R28) on svg2png [v3.1.1](https://github.com/domenic/svg2png/releases/tag/v3.1.1) breaks on node 4.5.0

I'm reverting to `1.0.2` until I have time to upgrade node to the next LTS.

I realise that you don't have control over the dependency. Perhaps adding a note saying something like _"Node 4 users please use version 1.x.x"_ to the readme would help other users that encounter the issue. 

Perhaps bumping the [`engine`](https://github.com/akoenig/gulp-svg2png/issues/26) version in the `package.json` can be included in a patch version.

**Comment by gagoar** [comment]
We had the same issue, 4.5 doesn't know about `es6 default arguments` (that's the line failing for us)
reverting to 1.0.2 as well.

**Comment by albybarber** [comment]
+1 I have had to do the same

**Comment by akoenig** [comment]
Hm, I'm not sure I understand. @mrkiffie did you use the `^2.0.0` version of `gulp-svg2png`? If so, this release has a proper set `engine` attribute in the [package.json](https://github.com/akoenig/gulp-svg2png/blob/a53c64fc45d73b50f4f125c3cb11305937bb5580/package.json#L15).

**Comment by mrkiffie** [comment]
Hi @akoenig.

I opened this issued for [`2.0.0`](https://github.com/akoenig/gulp-svg2png/releases/tag/2.0.0), when the [engine](https://github.com/akoenig/gulp-svg2png/blob/2.0.0/package.json) was still `^4.5.5`. This was resolved with [`2.0.1`](https://github.com/akoenig/gulp-svg2png/releases/tag/2.0.1)

At work we are still using node v4 LTS - so we will remain on [`1.0.2`](https://github.com/akoenig/gulp-svg2png/releases/tag/1.0.2) until we have upgrade to node v6 

I'm closing this issue 👍 

Thank you 🙂
