### ISSUE TITLE
Node 7

### ISSUE THREAD

**Issue by farwayer** [akoenig/gulp-svg2png#32]
```bash
master* $ yarn add --dev gulp-svg2png                                                                                        
yarn add v0.17.3
[1/4] Resolving packages...
warning gulp-svg2png > svg2png > phantomjs-prebuilt > request > node-uuid@1.4.7: use uuid module instead
[2/4] Fetching packages...
error gulp-svg2png@2.0.2: The engine "node" is incompatible with this module. Expected version "^6.0.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

master* $ node -v
v7.1.0
```

I think it's better to use something like `>=6.0.0` in `engines` field.

**Comment by sunnykgupta** [comment]
I think if these changes are merged, my npm install would start working. Currently giving error.

Any way I can work around while the author makes the change and releases?

**Comment by kingluddite** [comment]
Getting this error [screenshot](https://i.imgur.com/wGOH23t.png)

node v === v8.1.3

**Comment by deepio** [comment]
This error occurs when installing packages with `yarn`, but not with `npm`, regardless of the version of node. I believe this error message should at least be modified.
