### ISSUE TITLE
Display treatment logs

### ISSUE THREAD

**Issue by Delapouite** [akoenig/gulp-svg2png#5]
Hi

Converting massive collections of SVGs to PNGs files is a rather CPU intensive process even with recent machines. Currently there's no way to tell what's going on under the hood during a conversion task until it's has finished minutes later.

Would it be possible to add an optional output with gutil.log to display the file path of images already converted? Thanks.

**Comment by cspicuzza** [comment]
I'm having difficulty getting the progress log to display.  Here's my code sample incase you wanted to see it:

```
gulp.task('svg2png-test', function gulpTask(){

    return gulp.src(config.folders.originals + '/**/*.svg')
        .pipe(svg2png([{width: '32', height: '32'}, true, 5]))
        .on('error', handleErrors)
        .pipe(gulp.dest(config.folders.pngRaw + '/32'))
        .on('end', function(){ gutil.log(gutil.colors.green('Completed svg -> png 32') ) });
});

```
