### ISSUE TITLE
Getting an error when trying to run gulp-svg2png

### ISSUE THREAD

**Issue by Quirksmode** [akoenig/gulp-svg2png#9]
Reopening the closed issue as couldn't see a solution and I am having the same problem.

https://github.com/akoenig/gulp-svg2png/issues/2

My details are:

[gulp] CLI version 3.6.0
[gulp] Local version 3.8.10
NPM 2.1.9
Node v0.10.33

**Comment by agudulin** [comment]
Same problem.

```
$ gulp --version
[] CLI version 3.8.10
[] Local version 3.8.10

$ npm --version
2.1.18

$ node --version
v0.10.35
```

**Comment by Quirksmode** [comment]
My problem was caused by '#' being in the url path e.g. /#files/path/to/files

Removing it fixed it

**Comment by agudulin** [comment]
@Quirksmode oh, thanks, it helped.

**Comment by radu-tanasescu** [comment]
All I have in my image names are letters and underscores, it still fails.
